import type { Metadata } from 'next'
import { Providers } from '@/utils/apollo-provider'
import { Montserrat, Geist } from 'next/font/google'
import '@/styles/globals.css'
import { cn } from '@/lib/utils'
import Header from '@/components/shared/Header/Header'
import { AuthProvider } from '@/providers/auth.provider'

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' })

const montserrat = Montserrat({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Mebkvartal',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        montserrat.className,
        'font-sans',
        'font-sans',
        geist.variable
      )}
    >
      <body>
        <Providers>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  )
}
